# Generated by Django 2.2.9 on 2020-01-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='more',
            old_name='hood_id',
            new_name='home_id',
        ),
    ]
